"""initial schema

Revision ID: cfb43a2d33e1
Revises: 
Create Date: 2026-09-10 21:00:12.682650
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'cfb43a2d33e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('external_subject', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_subject')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(length=150), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('availability_window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('day_ordinal', sa.Integer(), nullable=True),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_window', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_window_day_ordinal'), ['day_ordinal'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_window_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_window_owner_type'), ['owner_type'], unique=False)

    op.create_table('constraint_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('constraint_weight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constraint_weight_code'), ['code'], unique=True)

    op.create_table('cycle_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weeks_in_cycle', sa.Integer(), nullable=False),
    sa.Column('granularity_minutes', sa.Integer(), nullable=False),
    sa.Column('lunch_start_minute', sa.Integer(), nullable=False),
    sa.Column('lunch_end_minute', sa.Integer(), nullable=False),
    sa.Column('lunch_break_minutes', sa.Integer(), nullable=False),
    sa.Column('early_threshold_minute', sa.Integer(), nullable=False),
    sa.Column('late_threshold_minute', sa.Integer(), nullable=False),
    sa.Column('max_student_minutes_per_day', sa.Integer(), nullable=False),
    sa.Column('individual_preferred_start', sa.Integer(), nullable=False),
    sa.Column('individual_preferred_end', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('week_index', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordinal', name='uq_day_ordinal')
    )
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_ordinal'), ['ordinal'], unique=False)

    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_index'), ['index'], unique=False)

    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('building', sa.String(length=64), nullable=True),
    sa.Column('floor', sa.String(length=32), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_building'), ['building'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_code'), ['code'], unique=True)

    op.create_table('room_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_feature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_feature_name'), ['name'], unique=True)

    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_group_code'), ['code'], unique=True)

    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_code'), ['code'], unique=True)

    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('max_minutes_per_day', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_external_id'), ['external_id'], unique=True)

    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('occurrences_per_cycle', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fixed_start_minute', sa.Integer(), nullable=True),
    sa.Column('fixed_room_id', sa.Integer(), nullable=True),
    sa.Column('align_to_periods', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('start_step_minutes', sa.Integer(), nullable=True),
    sa.Column('min_capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixed_room_id'], ['room.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_subject_id'), ['subject_id'], unique=False)

    op.create_table('room_feature_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['room_feature.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'feature_id', name='uq_room_feature')
    )
    with op.batch_alter_table('room_feature_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_feature_assignment_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_feature_assignment_room_id'), ['room_id'], unique=False)

    op.create_table('schedule_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('solver_run_id', sa.Integer(), nullable=True),
    sa.Column('total_penalty', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_version_id'], ['schedule_version.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_version_schedule_id'), ['schedule_id'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['class_group_id'], ['student_group.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_class_group_id'), ['class_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_external_id'), ['external_id'], unique=True)

    op.create_table('activity_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('activity_a_id', sa.Integer(), nullable=False),
    sa.Column('activity_b_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activity_a_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['activity_b_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_link_activity_a_id'), ['activity_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_link_activity_b_id'), ['activity_b_id'], unique=False)

    op.create_table('activity_room_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'room_id', 'kind', name='uq_activity_room_policy')
    )
    with op.batch_alter_table('activity_room_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_room_policy_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_room_policy_room_id'), ['room_id'], unique=False)

    op.create_table('activity_room_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_id'], ['room_feature.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'feature_id', name='uq_activity_requirement')
    )
    with op.batch_alter_table('activity_room_requirement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_room_requirement_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_room_requirement_feature_id'), ['feature_id'], unique=False)

    op.create_table('activity_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'student_id', name='uq_activity_student')
    )
    with op.batch_alter_table('activity_student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_student_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_student_student_id'), ['student_id'], unique=False)

    op.create_table('activity_student_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['student_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'group_id', name='uq_activity_group')
    )
    with op.batch_alter_table('activity_student_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_student_group_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_student_group_group_id'), ['group_id'], unique=False)

    op.create_table('activity_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'teacher_id', name='uq_activity_teacher')
    )
    with op.batch_alter_table('activity_teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_teacher_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_teacher_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('activity_time_window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('day_ordinal', sa.Integer(), nullable=True),
    sa.Column('start_minute', sa.Integer(), nullable=True),
    sa.Column('end_minute', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_time_window', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_time_window_activity_id'), ['activity_id'], unique=False)

    op.create_table('scheduled_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_index', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('day_ordinal', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('lock_time', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('lock_room', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['schedule_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_activity_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_activity_day_ordinal'), ['day_ordinal'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_activity_start_minute'), ['start_minute'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_activity_version_id'), ['version_id'], unique=False)

    op.create_table('solver_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('schedule_version_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('base_version_id', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('penalties', sa.JSON(), nullable=True),
    sa.Column('diagnostics', sa.JSON(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['base_version_id'], ['schedule_version.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['schedule_version.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solver_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solver_run_status'), ['status'], unique=False)

    op.create_table('student_group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['student_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'student_id', name='uq_group_student')
    )
    with op.batch_alter_table('student_group_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_group_member_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_group_member_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_group_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_group_member_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_group_member_group_id'))

    op.drop_table('student_group_member')
    with op.batch_alter_table('solver_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solver_run_status'))

    op.drop_table('solver_run')
    with op.batch_alter_table('scheduled_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_activity_version_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_activity_start_minute'))
        batch_op.drop_index(batch_op.f('ix_scheduled_activity_day_ordinal'))
        batch_op.drop_index(batch_op.f('ix_scheduled_activity_activity_id'))

    op.drop_table('scheduled_activity')
    with op.batch_alter_table('activity_time_window', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_time_window_activity_id'))

    op.drop_table('activity_time_window')
    with op.batch_alter_table('activity_teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_teacher_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_activity_teacher_activity_id'))

    op.drop_table('activity_teacher')
    with op.batch_alter_table('activity_student_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_student_group_group_id'))
        batch_op.drop_index(batch_op.f('ix_activity_student_group_activity_id'))

    op.drop_table('activity_student_group')
    with op.batch_alter_table('activity_student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_student_student_id'))
        batch_op.drop_index(batch_op.f('ix_activity_student_activity_id'))

    op.drop_table('activity_student')
    with op.batch_alter_table('activity_room_requirement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_room_requirement_feature_id'))
        batch_op.drop_index(batch_op.f('ix_activity_room_requirement_activity_id'))

    op.drop_table('activity_room_requirement')
    with op.batch_alter_table('activity_room_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_room_policy_room_id'))
        batch_op.drop_index(batch_op.f('ix_activity_room_policy_activity_id'))

    op.drop_table('activity_room_policy')
    with op.batch_alter_table('activity_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_link_activity_b_id'))
        batch_op.drop_index(batch_op.f('ix_activity_link_activity_a_id'))

    op.drop_table('activity_link')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_external_id'))
        batch_op.drop_index(batch_op.f('ix_student_class_group_id'))

    op.drop_table('student')
    with op.batch_alter_table('schedule_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_version_schedule_id'))

    op.drop_table('schedule_version')
    with op.batch_alter_table('room_feature_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_feature_assignment_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_feature_assignment_feature_id'))

    op.drop_table('room_feature_assignment')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_subject_id'))

    op.drop_table('activity')
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_external_id'))

    op.drop_table('teacher')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_code'))

    op.drop_table('subject')
    with op.batch_alter_table('student_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_group_code'))

    op.drop_table('student_group')
    op.drop_table('schedule')
    with op.batch_alter_table('room_feature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_feature_name'))

    op.drop_table('room_feature')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_code'))
        batch_op.drop_index(batch_op.f('ix_room_building'))

    op.drop_table('room')
    with op.batch_alter_table('period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_index'))

    op.drop_table('period')
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_ordinal'))

    op.drop_table('day')
    op.drop_table('cycle_config')
    with op.batch_alter_table('constraint_weight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constraint_weight_code'))

    op.drop_table('constraint_weight')
    with op.batch_alter_table('availability_window', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_window_owner_type'))
        batch_op.drop_index(batch_op.f('ix_availability_window_owner_id'))
        batch_op.drop_index(batch_op.f('ix_availability_window_day_ordinal'))

    op.drop_table('availability_window')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_email'))

    op.drop_table('app_user')
    # ### end Alembic commands ###
